actions:
  # Pre-user-registration actions
  enrich-signup-profile:
    name: "Enrich Signup Profile"
    trigger: "pre-user-registration"
    trigger_version: "v2"
    runtime: "node22"
    deploy: true
    order: 1
    environments: [dev, qa, val, prod]
    code: "main.js"
    dependencies: {}
    secrets_config:
      - "API_BASE_URL"
    secrets_pipeline: []
    modules:
      - module_key: "entry-path-verification"
      - module_key: "signup-validation"

  #Post-login actions
  enforce-email-verification:
    name: "Enforce Email Verification"
    trigger: "post-login"
    trigger_version: "v3"
    runtime: "node22"
    deploy: true
    order: 1
    environments: [dev]
    code: "main.js"
    dependencies: {}
    secrets_config:
      - "FORM_ID"
    secrets_pipeline: []

  complete-social-profile:
    name: "Complete Social Profile"
    trigger: "post-login"
    trigger_version: "v3"
    runtime: "node22"
    deploy: true
    order: 2
    environments: [dev]
    code: "main.js"
    dependencies: {}
    secrets_config:
      - "API_BASE_URL"
      - "PROFILE_FORM_ID"
      - "LINKING_FORM_ID"
    secrets_pipeline: []
    modules:
      - module_key: "account-linking"
      - module_key: "entry-path-verification"
      - module_key: "signup-validation"

  link-accounts:
    name: "Link Accounts"
    trigger: "post-login"
    trigger_version: "v3"
    runtime: "node22"
    deploy: true
    order: 3
    environments: [dev]
    code: "main.js"
    dependencies: {}
    secrets_config:
      - "LINKING_FORM_ID"
    secrets_pipeline: []
    modules:
      - module_key: "account-linking"

  post-account-linking:
    name: "Post Account Linking"
    trigger: "post-login"
    trigger_version: "v3"
    runtime: "node22"
    deploy: true
    order: 4
    environments: [dev]
    code: "main.js"
    dependencies: {}
    secrets_config:
      - "LINKING_SUCCESS_FORM_ID"
    secrets_pipeline: []

  custom-claims:
    name: "Custom Claims"
    trigger: "post-login"
    trigger_version: "v3"
    runtime: "node22"
    deploy: true
    order: 5
    environments: [dev]
    code: "main.js"
    dependencies: {}
    secrets_pipeline: []

  token-enrichment:
    name: "Token Enrichment"
    trigger: "post-login"
    trigger_version: "v3"
    runtime: "node22"
    deploy: true
    order: 6
    environments: [dev]
    code: "main.js"
    dependencies: {}
    secrets_pipeline: []

  token-check:
    name: "Token Check"
    trigger: "post-login"
    trigger_version: "v3"
    runtime: "node22"
    deploy: true
    order: 7
    environments: [dev]
    code: "main.js"
    dependencies: {}
    secrets_pipeline: []
