# Auth0 action definitions.
# https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/action
#
# environments: Optional list of envs where this action should exist.
#               Omit = created in all environments.
#
# testing: Optional block to route specific envs to next.js.
#
# Order of actions = execution order per trigger.
actions:
  enrich-signup-profile:
    name: "Enrich Signup Profile"
    trigger: "pre-user-registration"
    trigger_version: "v2"
    runtime: "node22"
    deploy: true
    code: "main.js"
    dependencies: {}
    secrets_config:
      - "API_BASE_URL"
    secrets_pipeline: []
    modules:
      - module_key: "entry-path-verification"
      - module_key: "signup-validation"
