# Auth0 action module definitions.
# https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/action_module
#
# environments: Optional list of envs where this module should exist.
#               Omit = created in all environments.
#               Example: environments: ["dev", "qa"]
#
# testing: Optional block to route specific envs to next.js during development.
action_modules:
  entry-path-verification:
    name: "Entry Path Verification"
    publish: true
    code: "main.js"
    dependencies: {}
    secrets_pipeline: []

  account-linking:
    name: "Account Linking"
    publish: true
    code: "main.js"
    dependencies:
      auth0: "latest"
    secrets_config:
      - "MANAGEMENT_API_DOMAIN"
      - "MANAGEMENT_API_CLIENT_ID"
    secrets_pipeline:
      - "MANAGEMENT_API_CLIENT_SECRET"

  signup-validation:
    name: "Signup Validation"
    publish: true
    code: "main.js"
    dependencies:
      joi: "latest"
      libphonenumber-js: "latest"
    secrets_pipeline: []
