# PROD environment configuration.
auth0_domain: "REPLACE_WITH_PROD_DOMAIN"
region: "na"

marlo_callbacks:   ["https://marlo.example.com/callback"]
marlo_logout_urls: ["https://marlo.example.com"]
marlo_web_origins: ["https://marlo.example.com"]

vault_auth0_domain:    "REPLACE_WITH_PROD_DOMAIN"
vault_auth0_client_id: "REPLACE_WITH_PROD_VAULT_CLIENT_ID"

management_api_domain:    "REPLACE_WITH_PROD_DOMAIN"
management_api_client_id: "REPLACE_WITH_PROD_MGMT_CLIENT_ID"

api_base_url: "REPLACE_WITH_PROD_API_URL"
